# -*- coding: utf-8 -*-
"""青空文庫からルビなど取り除く

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FbzhY5Rzy7_cIgu56rRRhGd63G29lYNp

## 概要

青空文庫からzip形式でファイルをダウンロードし、ルビを取り除いて、textファイルでダウンロードします。

## 書籍の指定
"""

# [青空文庫](https://www.aozora.gr.jp)掲載の書籍から一つ選び、zip形式でURLを指定します。
# 銀河鉄道の夜( https://www.aozora.gr.jp/cards/000081/card456.html )の場合は以下のとおりです。

URL = 'https://www.aozora.gr.jp/cards/000081/files/456_ruby_145.zip'
OUTPUT_FILE = 'output.txt'

"""## インストール & インポート"""

!apt-get install mecab
!apt-get install libmecab-dev
!apt-get install mecab-ipadic-utf8
!pip install mecab-python3

import re
import zipfile
import urllib.request
import os.path,glob

"""## ファンクションの定義"""

def download(url):
  zip_file = re.split(r'/', url)[-1]

  if not os.path.exists(zip_file):
    print('Download URL')
    print('URL:',url)
    urllib.request.urlretrieve(url, zip_file)
  else:
     print('Download File exists')

  dir, ext = os.path.splitext(zip_file)
  if not os.path.exists(dir):
     os.makedirs(dir)

  # open zip
  zip_obj = zipfile.ZipFile(zip_file, 'r')
  zip_obj.extractall(dir)
  zip_obj.close()

  # delete zip
  os.remove(zip_file)

  # get text file path
  path = os.path.join(dir,'*.txt')
  list = glob.glob(path)
  return list[0]



def convert(download_text):
  binarydata = open(download_text, 'rb').read()
  text = binarydata.decode('shift_jis')

  text = re.split(r'\-{5,}', text)[2]
  text = re.split(r'底本：', text)[0]
  text = re.sub(r'《.+?》', '', text)
  text = re.sub(r'［＃.+?］', '', text)
  text = re.sub(r'\u3000', '', text)
  text = re.sub(r'\r\n', '', text)
  text = text.strip()
  return text

"""convert() は 青空文庫にはルビが入っていたり、行末に本文とは関係のない文字が含まれているのでそれらを削除します。

※ 文章初めの全角スペースや、改行も一緒に削除しています。

## 実行
"""

# zipファイルをダウンロードして、文章を取り出します。
download_file = download(URL)

# 取り出した文章から、ルビなどの余計な文字を取り除きます。
text = convert(download_file)
text

# ファイルとして保存します
with open(OUTPUT_FILE,"w") as f:
  f.write(text)
!ls

# ファイルをダウンロードします
from google.colab import files
files.download(OUTPUT_FILE)